vars:
  PACKAGE_NAME:
    default: app.tulx.tldraw
  APP_NAME:
    default: Tldraw
  VERSION_NAME:
    default: "0.0.1"
    type: string
  VERSION_NAME_SUFFIX:
    default:
  VERSION_CODE:
    default: 1
    type: number
  INCREMENTAL_VERSION_CODE:
    default: true

platforms:
  android:
    appName: $APP_NAME
    versionName: $VERSION_NAME
    versionCode: $VERSION_CODE
    # incrementVersionCode: $INCREMENTAL_VERSION_CODE
    # versionNameSuffix: $VERSION_NAME_SUFFIX
    packageName: $PACKAGE_NAME
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        attrs:
          xmlns:tools: http://schemas.android.com/tools

      - file: AndroidManifest.xml
        target: manifest/application
        attrs:
          android:largeHeap: true
          android:hardwareAccelerated: true

      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <manifest>
            <!-- <uses-permission android:name="android.permission.CAMERA" /> -->
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" />
          </manifest>

      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <manifest>
            <uses-sdk tools:overrideLibrary="com.google.zxing.client.android" />
          </manifest>
