name: Nldraw CI

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

  workflow_dispatch:
    inputs:
      description:
        required: true
        description: A short description for this manual dispatch
        type: string

env:
  APK_FILE: ${{ inputs.description || github.ref_name }}.apk

jobs:
  build:
    name: Build
    if: inputs.description || github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Clean install dependencies
        run: npm ci

      - name: Prepare dist
        run: mkdir dist && touch dist/index.html
        continue-on-error: true

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Fix gradlew permissions
        run: chmod +x android/gradlew

      - name: Sync web assets with native
        run: npm run sync:android

      - name: Create release APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Sign release APK
        id: sign_release
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Move and rename signed APK
        run: cp ${{ steps.sign_release.outputs.signedReleaseFile }} ${{ env.APK_FILE }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Signed ${{ env.APK_FILE }}
          path: ${{ env.APK_FILE }}

      - name: Release ${{ github.ref_name }}
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APK_FILE }}
